### ISSUE TITLE
Image encoder clarification

### ISSUE THREAD

**Issue by gbenms** [wl-zhao/VPD#10]
Hi,
thank you for sharing this interesting work.
could you please share which encoder is used to encode the images to latent space? 
In the paper, you mention using a frozen VQGAN encoder. However, in the vi_inference.yaml configuration file used to set up stable diffusion, a kl-autoencoder is used as the first stage model.
thanks!

**Comment by wl-zhao** [comment]
Hi,

Thanks for your careful reading. We use the kl-autoencoder for the first-stage model, the same as the text-to-image diffusion model in stable-diffusion. Perhaps because many other models in stable-diffusion (such as ffhq256, cin256, etc) adopt the VQGAN as the first-stage model, VQGAN is often used to indicate the first stage of a stable-diffusion model, despite the slight difference in actual implementation. We will modify it in the updated version of our paper to avoid misunderstanding.

Thanks,
Wenliang
